/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface MemeA8FactoryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "bridge"
      | "createMeme"
      | "createMemeWithoutLaunching"
      | "creationFee"
      | "fee"
      | "feeTo"
      | "forLaunching"
      | "getMemeAddress"
      | "implementation"
      | "initialize"
      | "initializeWithoutLaunching"
      | "listingFee"
      | "native"
      | "owner"
      | "renounceOwnership"
      | "setBridge"
      | "setCreationFee"
      | "setFee"
      | "setFeeTo"
      | "setForLaunching"
      | "setImplementation"
      | "setListingFee"
      | "setNative"
      | "setSignerAddress"
      | "setUniV2Factory"
      | "signerAddress"
      | "transferOwnership"
      | "uniswapV2Factory"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BridgeSet"
      | "ConfigurationSet"
      | "ImplementationSet"
      | "Initialized"
      | "MemeCreated"
      | "MemeCreatedWithoutLaunching"
      | "OwnershipTransferred"
      | "SignerSet"
  ): EventFragment;

  encodeFunctionData(functionFragment: "bridge", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "createMeme",
    values: [
      string,
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "createMemeWithoutLaunching",
    values: [string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "creationFee",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "fee", values?: undefined): string;
  encodeFunctionData(functionFragment: "feeTo", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "forLaunching",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getMemeAddress",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "implementation",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [
      AddressLike,
      AddressLike,
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      AddressLike,
      AddressLike,
      AddressLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "initializeWithoutLaunching",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "listingFee",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "native", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setBridge",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setCreationFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setFeeTo",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setForLaunching",
    values: [boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setImplementation",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setListingFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setNative",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setSignerAddress",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setUniV2Factory",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "signerAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "uniswapV2Factory",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "bridge", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "createMeme", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createMemeWithoutLaunching",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "creationFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "fee", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "feeTo", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "forLaunching",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMemeAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "implementation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "initializeWithoutLaunching",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "listingFee", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "native", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setBridge", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setCreationFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setFee", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setFeeTo", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setForLaunching",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setImplementation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setListingFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setNative", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setSignerAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setUniV2Factory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "signerAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "uniswapV2Factory",
    data: BytesLike
  ): Result;
}

export namespace BridgeSetEvent {
  export type InputTuple = [arg0: AddressLike];
  export type OutputTuple = [arg0: string];
  export interface OutputObject {
    arg0: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ConfigurationSetEvent {
  export type InputTuple = [
    feeTo: AddressLike,
    fee: BigNumberish,
    listingFee: BigNumberish,
    creationFee: BigNumberish,
    native: AddressLike,
    uniswapV2Factory: AddressLike,
    forLaunching: boolean
  ];
  export type OutputTuple = [
    feeTo: string,
    fee: bigint,
    listingFee: bigint,
    creationFee: bigint,
    native: string,
    uniswapV2Factory: string,
    forLaunching: boolean
  ];
  export interface OutputObject {
    feeTo: string;
    fee: bigint;
    listingFee: bigint;
    creationFee: bigint;
    native: string;
    uniswapV2Factory: string;
    forLaunching: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ImplementationSetEvent {
  export type InputTuple = [arg0: AddressLike];
  export type OutputTuple = [arg0: string];
  export interface OutputObject {
    arg0: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InitializedEvent {
  export type InputTuple = [version: BigNumberish];
  export type OutputTuple = [version: bigint];
  export interface OutputObject {
    version: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MemeCreatedEvent {
  export type InputTuple = [
    meme: AddressLike,
    creator: AddressLike,
    totalSupply: BigNumberish,
    saleAmount: BigNumberish,
    tokenOffset: BigNumberish,
    nativeOffset: BigNumberish,
    tokenId: BigNumberish
  ];
  export type OutputTuple = [
    meme: string,
    creator: string,
    totalSupply: bigint,
    saleAmount: bigint,
    tokenOffset: bigint,
    nativeOffset: bigint,
    tokenId: bigint
  ];
  export interface OutputObject {
    meme: string;
    creator: string;
    totalSupply: bigint;
    saleAmount: bigint;
    tokenOffset: bigint;
    nativeOffset: bigint;
    tokenId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MemeCreatedWithoutLaunchingEvent {
  export type InputTuple = [meme: AddressLike, tokenId: BigNumberish];
  export type OutputTuple = [meme: string, tokenId: bigint];
  export interface OutputObject {
    meme: string;
    tokenId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SignerSetEvent {
  export type InputTuple = [arg0: AddressLike];
  export type OutputTuple = [arg0: string];
  export interface OutputObject {
    arg0: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MemeA8Factory extends BaseContract {
  connect(runner?: ContractRunner | null): MemeA8Factory;
  waitForDeployment(): Promise<this>;

  interface: MemeA8FactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  bridge: TypedContractMethod<[], [string], "view">;

  createMeme: TypedContractMethod<
    [
      _name: string,
      _symbol: string,
      _tokenId: BigNumberish,
      _tokenOffset: BigNumberish,
      _nativeOffset: BigNumberish,
      _totalSupply: BigNumberish,
      _saleAmount: BigNumberish,
      _initialDeposit: BigNumberish,
      _whitelistEndTs: BigNumberish
    ],
    [string],
    "nonpayable"
  >;

  createMemeWithoutLaunching: TypedContractMethod<
    [_name: string, _symbol: string, _tokenId: BigNumberish],
    [string],
    "nonpayable"
  >;

  creationFee: TypedContractMethod<[], [bigint], "view">;

  fee: TypedContractMethod<[], [bigint], "view">;

  feeTo: TypedContractMethod<[], [string], "view">;

  forLaunching: TypedContractMethod<[], [boolean], "view">;

  getMemeAddress: TypedContractMethod<
    [_tokenId: BigNumberish],
    [string],
    "view"
  >;

  implementation: TypedContractMethod<[], [string], "view">;

  initialize: TypedContractMethod<
    [
      _implementation: AddressLike,
      _signerAddress: AddressLike,
      _feeTo: AddressLike,
      _fee: BigNumberish,
      _creationFee: BigNumberish,
      _listingFee: BigNumberish,
      _bridge: AddressLike,
      _univ2Factory: AddressLike,
      _native: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  initializeWithoutLaunching: TypedContractMethod<
    [_implementation: AddressLike],
    [void],
    "nonpayable"
  >;

  listingFee: TypedContractMethod<[], [bigint], "view">;

  native: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setBridge: TypedContractMethod<[_bridge: AddressLike], [void], "nonpayable">;

  setCreationFee: TypedContractMethod<
    [_creationFee: BigNumberish],
    [void],
    "nonpayable"
  >;

  setFee: TypedContractMethod<[_fee: BigNumberish], [void], "nonpayable">;

  setFeeTo: TypedContractMethod<[_feeTo: AddressLike], [void], "nonpayable">;

  setForLaunching: TypedContractMethod<
    [_forLaunching: boolean],
    [void],
    "nonpayable"
  >;

  setImplementation: TypedContractMethod<
    [_implementation: AddressLike],
    [void],
    "nonpayable"
  >;

  setListingFee: TypedContractMethod<
    [_listingFee: BigNumberish],
    [void],
    "nonpayable"
  >;

  setNative: TypedContractMethod<[_native: AddressLike], [void], "nonpayable">;

  setSignerAddress: TypedContractMethod<
    [_signer: AddressLike],
    [void],
    "nonpayable"
  >;

  setUniV2Factory: TypedContractMethod<
    [_univ2Factory: AddressLike],
    [void],
    "nonpayable"
  >;

  signerAddress: TypedContractMethod<[], [string], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  uniswapV2Factory: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "bridge"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "createMeme"
  ): TypedContractMethod<
    [
      _name: string,
      _symbol: string,
      _tokenId: BigNumberish,
      _tokenOffset: BigNumberish,
      _nativeOffset: BigNumberish,
      _totalSupply: BigNumberish,
      _saleAmount: BigNumberish,
      _initialDeposit: BigNumberish,
      _whitelistEndTs: BigNumberish
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createMemeWithoutLaunching"
  ): TypedContractMethod<
    [_name: string, _symbol: string, _tokenId: BigNumberish],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "creationFee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "fee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "feeTo"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "forLaunching"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "getMemeAddress"
  ): TypedContractMethod<[_tokenId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "implementation"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<
    [
      _implementation: AddressLike,
      _signerAddress: AddressLike,
      _feeTo: AddressLike,
      _fee: BigNumberish,
      _creationFee: BigNumberish,
      _listingFee: BigNumberish,
      _bridge: AddressLike,
      _univ2Factory: AddressLike,
      _native: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "initializeWithoutLaunching"
  ): TypedContractMethod<[_implementation: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "listingFee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "native"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setBridge"
  ): TypedContractMethod<[_bridge: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setCreationFee"
  ): TypedContractMethod<[_creationFee: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setFee"
  ): TypedContractMethod<[_fee: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setFeeTo"
  ): TypedContractMethod<[_feeTo: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setForLaunching"
  ): TypedContractMethod<[_forLaunching: boolean], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setImplementation"
  ): TypedContractMethod<[_implementation: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setListingFee"
  ): TypedContractMethod<[_listingFee: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setNative"
  ): TypedContractMethod<[_native: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setSignerAddress"
  ): TypedContractMethod<[_signer: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setUniV2Factory"
  ): TypedContractMethod<[_univ2Factory: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "signerAddress"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "uniswapV2Factory"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "BridgeSet"
  ): TypedContractEvent<
    BridgeSetEvent.InputTuple,
    BridgeSetEvent.OutputTuple,
    BridgeSetEvent.OutputObject
  >;
  getEvent(
    key: "ConfigurationSet"
  ): TypedContractEvent<
    ConfigurationSetEvent.InputTuple,
    ConfigurationSetEvent.OutputTuple,
    ConfigurationSetEvent.OutputObject
  >;
  getEvent(
    key: "ImplementationSet"
  ): TypedContractEvent<
    ImplementationSetEvent.InputTuple,
    ImplementationSetEvent.OutputTuple,
    ImplementationSetEvent.OutputObject
  >;
  getEvent(
    key: "Initialized"
  ): TypedContractEvent<
    InitializedEvent.InputTuple,
    InitializedEvent.OutputTuple,
    InitializedEvent.OutputObject
  >;
  getEvent(
    key: "MemeCreated"
  ): TypedContractEvent<
    MemeCreatedEvent.InputTuple,
    MemeCreatedEvent.OutputTuple,
    MemeCreatedEvent.OutputObject
  >;
  getEvent(
    key: "MemeCreatedWithoutLaunching"
  ): TypedContractEvent<
    MemeCreatedWithoutLaunchingEvent.InputTuple,
    MemeCreatedWithoutLaunchingEvent.OutputTuple,
    MemeCreatedWithoutLaunchingEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "SignerSet"
  ): TypedContractEvent<
    SignerSetEvent.InputTuple,
    SignerSetEvent.OutputTuple,
    SignerSetEvent.OutputObject
  >;

  filters: {
    "BridgeSet(address)": TypedContractEvent<
      BridgeSetEvent.InputTuple,
      BridgeSetEvent.OutputTuple,
      BridgeSetEvent.OutputObject
    >;
    BridgeSet: TypedContractEvent<
      BridgeSetEvent.InputTuple,
      BridgeSetEvent.OutputTuple,
      BridgeSetEvent.OutputObject
    >;

    "ConfigurationSet(address,uint256,uint256,uint256,address,address,bool)": TypedContractEvent<
      ConfigurationSetEvent.InputTuple,
      ConfigurationSetEvent.OutputTuple,
      ConfigurationSetEvent.OutputObject
    >;
    ConfigurationSet: TypedContractEvent<
      ConfigurationSetEvent.InputTuple,
      ConfigurationSetEvent.OutputTuple,
      ConfigurationSetEvent.OutputObject
    >;

    "ImplementationSet(address)": TypedContractEvent<
      ImplementationSetEvent.InputTuple,
      ImplementationSetEvent.OutputTuple,
      ImplementationSetEvent.OutputObject
    >;
    ImplementationSet: TypedContractEvent<
      ImplementationSetEvent.InputTuple,
      ImplementationSetEvent.OutputTuple,
      ImplementationSetEvent.OutputObject
    >;

    "Initialized(uint8)": TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;
    Initialized: TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;

    "MemeCreated(address,address,uint256,uint256,uint256,uint256,uint256)": TypedContractEvent<
      MemeCreatedEvent.InputTuple,
      MemeCreatedEvent.OutputTuple,
      MemeCreatedEvent.OutputObject
    >;
    MemeCreated: TypedContractEvent<
      MemeCreatedEvent.InputTuple,
      MemeCreatedEvent.OutputTuple,
      MemeCreatedEvent.OutputObject
    >;

    "MemeCreatedWithoutLaunching(address,uint256)": TypedContractEvent<
      MemeCreatedWithoutLaunchingEvent.InputTuple,
      MemeCreatedWithoutLaunchingEvent.OutputTuple,
      MemeCreatedWithoutLaunchingEvent.OutputObject
    >;
    MemeCreatedWithoutLaunching: TypedContractEvent<
      MemeCreatedWithoutLaunchingEvent.InputTuple,
      MemeCreatedWithoutLaunchingEvent.OutputTuple,
      MemeCreatedWithoutLaunchingEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "SignerSet(address)": TypedContractEvent<
      SignerSetEvent.InputTuple,
      SignerSetEvent.OutputTuple,
      SignerSetEvent.OutputObject
    >;
    SignerSet: TypedContractEvent<
      SignerSetEvent.InputTuple,
      SignerSetEvent.OutputTuple,
      SignerSetEvent.OutputObject
    >;
  };
}
